Repository itsnporg/Simple-Programs, pull requests merged in 2021-10, with the labels that each got.

#40 program to calculate armstrong number in C
  C-Programs/armstrong_number.c
Labels: hacktoberfest-accepted

#39 Quotient and remainder calc.c
  C-Programs/Quotient and remainder calc.c
Labels: hacktoberfest-accepted

#44 stack application-add balancedparenthesis.py
  C-Programs/Coinchange.c
  Python-Programs/Python Numpy library/.ipynb_checkpoints/Numpy basics-checkpoint.ipynb
  Python-Programs/Python Numpy library/Numpy basics.ipynb
Labels: hacktoberfest-accepted

#72 Create C++ finding factorial by recursion
  finding-factorial-by-recursion.cpp
Labels: hacktoberfest-accepted

#80 Sum of leaf nodes in BST using recursive approach
  C++ Programs/sum-of-leaf-nodes-in-BST.cpp
Labels: hacktoberfest-accepted

#59 Fibonacci-series.c
  C-Programs/Fibonacci series.c
Labels: hacktoberfest-accepted

#29 added joke fetcher
  Python-Programs/jokes.py
Labels: hacktoberfest-accepted

#112 Create function-overloading.cpp
  C++-Programs/function-overloading.cpp
  Python-Programs/Discord/qrcode-generate-bot.py
Labels: waiting for response

#225 added python script to get placeholder images
  Python-Programs/placeholder_images/placeholder.py
Labels: hacktoberfest-accepted

#219 Countdown Timer in Js
  JavaScript-Programs/countdown-timer.js
Labels: hacktoberfest-accepted

#228 Created PermuteString.js file
  JavaScript-Programs/PermutateString.js
Labels: hacktoberfest-accepted

#236 Create prims_algorithm.c
  C-Programs/prims_algorithm.c
Labels: hacktoberfest-accepted

#240 js closure added
  JavaScript-Programs/closure.js
Labels: hacktoberfest-accepted

#241 Added new C socket server-client project.
  C-Programs/socket/README.md
  C-Programs/socket/build.sh
  C-Programs/socket/build_client.sh
  C-Programs/socket/build_server.sh
  C-Programs/socket/src/client/client.c
  C-Programs/socket/src/client/client.h
  C-Programs/socket/src/client/client_main.c
  C-Programs/socket/src/server/server.c
  C-Programs/socket/src/server/server.h
  C-Programs/socket/src/server/server_main.c
  Python-Programs/download_pdf.py
Labels: hacktoberfest-accepted

#255 used list comprehension to take input
  Python-Programs/addition.py
Labels: hacktoberfest-accepted

#258 Added function
  C-Programs/Palindrome.c
Labels: hacktoberfest-accepted

#217 hello world
  Rust-Programs/helloworld.rs
Labels: hacktoberfest-accepted

#246 Number guessing game using python
  Python-Programs/guess.py
Labels: hacktoberfest-accepted

#239 added: arrayadd.js
  JavaScript-Programs/arrayadd.js
Labels: hacktoberfest-accepted

#238 JS program fetch ChuckNorris Jokes and log them.
  JavaScript-Programs/Fetch_jokes.js
Labels: hacktoberfest-accepted

#253 c# simple calculator
  C#-Programs/calculater/Program.cs
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.deps.json
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.dll
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.exe
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.pdb
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.runtimeconfig.dev.json
  C#-Programs/calculater/bin/Debug/netcoreapp3.1/calculater.runtimeconfig.json
  C#-Programs/calculater/calculater.csproj
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.AssemblyInfo.cs
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.AssemblyInfoInputs.cache
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.assets.cache
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.csproj.CoreCompileInputs.cache
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.csproj.FileListAbsolute.txt
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.csprojAssemblyReference.cache
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.dll
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.exe
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.genruntimeconfig.cache
  C#-Programs/calculater/obj/Debug/netcoreapp3.1/calculater.pdb
  C#-Programs/calculater/obj/calculater.csproj.nuget.dgspec.json
  C#-Programs/calculater/obj/calculater.csproj.nuget.g.props
  C#-Programs/calculater/obj/calculater.csproj.nuget.g.targets
  C#-Programs/calculater/obj/project.assets.json
  C#-Programs/calculater/obj/project.nuget.cache
Labels: hacktoberfest-accepted

#261 Python program to reverse a entered number
  Python-Programs/reverse.py
Labels: hacktoberfest-accepted

#262 promise chaining function example
  JavaScript-Programs/promise-chaining.js
Labels: hacktoberfest-accepted

#257 Subsets generating problem
  C++-Programs/Generate_Subsets.cpp
Labels: hacktoberfest-accepted

#256 Add beginner-intermediate programs for Ruby
  Other-Languages/Ruby/AluCrossPlus/.gitignore
  Other-Languages/Ruby/AluCrossPlus/Game.rb
  Other-Languages/Ruby/AluCrossPlus/README.md
  Other-Languages/Ruby/AluCrossPlus/clear_screen.rb
  Other-Languages/Ruby/AluCrossPlus/main.rb
  Other-Languages/Ruby/RubyTodo/.gitignore
  Other-Languages/Ruby/RubyTodo/.idea/.gitignore
  Other-Languages/Ruby/RubyTodo/.idea/RubyTodo.iml
  Other-Languages/Ruby/RubyTodo/.idea/misc.xml
  Other-Languages/Ruby/RubyTodo/.idea/modules.xml
  Other-Languages/Ruby/RubyTodo/.idea/sqldialects.xml
  Other-Languages/Ruby/RubyTodo/.idea/vcs.xml
  Other-Languages/Ruby/RubyTodo/.rspec
  Other-Languages/Ruby/RubyTodo/App.rb
  Other-Languages/Ruby/RubyTodo/Database.rb
  Other-Languages/Ruby/RubyTodo/Gemfile
  Other-Languages/Ruby/RubyTodo/Gemfile.lock
  Other-Languages/Ruby/RubyTodo/README.md
  Other-Languages/Ruby/RubyTodo/Session.rb
  Other-Languages/Ruby/RubyTodo/Todo.rb
  Other-Languages/Ruby/RubyTodo/User.rb
  Other-Languages/Ruby/RubyTodo/clear_screen.rb
  Other-Languages/Ruby/RubyTodo/main.rb
  Other-Languages/Ruby/RubyTodo/spec/database_spec.rb
  Other-Languages/Ruby/RubyTodo/spec/spec_helper.rb
  Other-Languages/Ruby/RubyTodo/spec/todo_spec.rb
  Other-Languages/Ruby/RubyTodo/test.db
Labels: hacktoberfest-accepted

#252 Create find_factor.js
  C++-Programs/simple_pattern.cpp
  JavaScript-Programs/find_factor.js
Labels: hacktoberfest-accepted

#254 Add some latest problems of codechef
  Competitive Programming/Codechef Problems/CC_START2_BUYPLSE.cpp
  Competitive Programming/Codechef Problems/CC_START2_DIFACTRS.cpp
  Competitive Programming/Codechef Problems/CC_START2_ISBOTH.cpp
  Competitive Programming/Codechef Problems/CC_START2_RNGEODD.c
  Competitive Programming/Codechef Problems/CC_START2_SECLAR.cpp
  Competitive Programming/Codechef Problems/CC_START2_VALTRI.c
  Competitive Programming/Codechef Problems/COOK133C_ADJHATE.cpp
  Competitive Programming/Codechef Problems/COOK133C_FAKEGCD.cpp
  Competitive Programming/Codechef Problems/LTIME100C_TWODISH.cpp
  Competitive Programming/Codechef Problems/LTIME100C_UNQEQ.cpp
  Competitive Programming/Codechef Problems/LTIME100C_VDATES.cpp
  Competitive Programming/Codechef Problems/PRACTICE(SCHOOL)_SOD3.cpp
  Competitive Programming/Codechef Problems/SDPC_B21_KTTABLE.cpp
  Competitive Programming/Codechef Problems/SDPC_B21_SNAKPROC.cpp
  Competitive Programming/Codechef Problems/START12C_GOODWEAT.cpp
  Competitive Programming/Codechef Problems/START12C_MAKEDIV3.cpp
  Competitive Programming/Codechef Problems/START13C_DIWALI1.cpp
  Competitive Programming/Codechef Problems/START13C_MAGDOORS.cpp
  Competitive Programming/Codechef Problems/START13C_SUPCHEF.cpp
  Competitive Programming/Codechef Problems/START13C_VACCINQ.cpp
  Competitive Programming/Codechef Problems/START14C_BININV.cpp
  Competitive Programming/Codechef Problems/START14C_DIAGMOVE.cpp
  Competitive Programming/Codechef Problems/START14C_FIXFIX.cpp
  Competitive Programming/Codechef Problems/START14C_RCBPLAY.py
Labels: hacktoberfest-accepted

#230 added : neuralxor.js
  JavaScript-Programs/neuralxor.js
Labels: hacktoberfest-accepted

#207 Javascript Sorting Algorithms
  JavaScript-Programs/Sorting-Algorithms/BubbleSort.js
  JavaScript-Programs/Sorting-Algorithms/InsertionSort.js
  JavaScript-Programs/Sorting-Algorithms/MergeSort.js
  JavaScript-Programs/Sorting-Algorithms/QuickSort.js
Labels: hacktoberfest-accepted

#263 for loop
  GoLang-Programs/forloop.go
Labels: hacktoberfest-accepted

#180 Create bubbleSort.js
  JavaScript-Programs/bubbleSort.js
Labels: hacktoberfest-accepted

#216 python program to check if the number is armstrong or not
  Python-Programs/check-armstrong-number.py
Labels: hacktoberfest-accepted

#277 c program for selection sort
  C-Programs/selection_sort.c
Labels: hacktoberfest-accepted

#244 added erlang hello world
  Other-Languages/Erlang/hello.beam
  Other-Languages/Erlang/hello.erl
Labels: hacktoberfest-accepted

#234 Added Celsius to Fahrenheit converting program
  Other-Languages/Java/CelsiusToFahrenheit.java
Labels: hacktoberfest-accepted

#173 A program on Sentiment analysis
  Python-Programs/Sentiment_analysis.py
Labels: hacktoberfest-accepted

#212 Python program for a Binary Search Tree
  Python-Programs/Binary_search_tree.py
Labels: waiting for response

#294 simple guessing game
  Rust-Programs/guessing_game/Cargo.lock
  Rust-Programs/guessing_game/Cargo.toml
  Rust-Programs/guessing_game/src/main.rs
Labels: hacktoberfest-accepted

#327 Added a new file motion-detector.py
  Python-Programs/motion-detector.py
Labels: hacktoberfest-accepted

#324 Create maximum_subarray_sum.cpp
  C++-Programs/maximum_subarray_sum.cpp
Labels: hacktoberfest-accepted

#322 Added bogosort source code in Cpp
  C++-Programs/bogosort.cpp
Labels: hacktoberfest-accepted

#318 Added program to solve cannibals and missionaries game
  Python-Programs/cannibals.py
Labels: hacktoberfest-accepted

#315 Hangman in C
  C-Programs/Hangman.c
Labels: hacktoberfest-accepted, waiting for response

#302 Shopping Cart JS
  JavaScript-Programs/shoppingCart.js
Labels: hacktoberfest-accepted

#313 Ceaser cypher encryption in python
  Python-Programs/ceaser_cypher_encryption.py
Labels: hacktoberfest-accepted

#312 Create snakegame.py
  Python-Programs/snakegame.py
Labels: hacktoberfest-accepted

#310 LFU Cache Implementation
  C++-Programs/LFU_Implementation
Labels: hacktoberfest-accepted

#328 number is prime or not
  Java-Programs/Prime.java
Labels: hacktoberfest-accepted

#296 Create Narutoquotes.js
  JavaScript-Programs/Narutoquotes.js
Labels: hacktoberfest-accepted

#329 Added a new folder checksum_python
  Python-Programs/checksum_python/receiver.py
  Python-Programs/checksum_python/sender.py
Labels: hacktoberfest-accepted

#334 Added program to clone a linked list
  C++-Programs/clone-linked-list.cpp
Labels: hacktoberfest-accepted

#336 Added a new folder chat_app
  Python-Programs/chat_app/client.py
  Python-Programs/chat_app/server.py
Labels: hacktoberfest-accepted

#340 pyramid
  Python-Programs/pyramid.py
Labels: hacktoberfest-accepted

#342 A competitive programming question
  Competitive Programming/removingIslands.py
Labels: hacktoberfest-accepted

#341 added remove duplicate elements using java
  Java-Programs/RemoveDuplicate.java
Labels: hacktoberfest-accepted

#332 Create addTwoNumbers
  Rust-Programs/addTwoNumbers.rs
Labels: hacktoberfest-accepted

#333 Create virtual_function_example.cpp
  C++-Programs/virtual_function_example.cpp
Labels: hacktoberfest-accepted

#344 Checking for graph is Bipartite Graph or not
  C++-Programs/bipartiteGraphdfs.cpp
Labels: hacktoberfest-accepted

#269 input
  GoLang-Programs/input.go
Labels: hacktoberfest-accepted

#206 Javascript Algorithms - 1
  JavaScript-Programs/Algorithms/binarySearch.js
  JavaScript-Programs/Algorithms/bubbleSort.js
  JavaScript-Programs/Algorithms/linearSearch.js
Labels: hacktoberfest-accepted

#343 AgnosticBinarySearch.java and Linear_Search_In_2D_Array.java added
  Java-Programs/AgnosticBinarySearch.java
  Java-Programs/LinearSearch2DArray.java
Labels: hacktoberfest-accepted

#193 Create Jumbler.py
  Python-Programs/Jumbler.py
Labels: hacktoberfest-accepted

#189 Program to convert temperature in js
  JavaScript-Programs/temperature-converter.js
Labels: waiting for response

#330 Added a new folder file-transfer
  Python-Programs/file_transfer/data.txt
  Python-Programs/file_transfer/file_client.py
  Python-Programs/file_transfer/file_server.py
  Python-Programs/file_transfer/receiveddata.txt
Labels: hacktoberfest-accepted

#274 Create for_each
  GoLang-Programs/for_each.go
Labels: hacktoberfest-accepted

#268 (rechecked and bugfixes ) python program which autoplots graph using users input file
  Python-Programs/autoplot-maker/find_file.py
  Python-Programs/autoplot-maker/index.py
  Python-Programs/autoplot-maker/plot.py
  Python-Programs/autoplot-maker/prediction.py
  Python-Programs/autoplot-maker/statistics.py
Labels: hacktoberfest-accepted

#345 Add LongestPalindromeSubstring.cpp
  C++-Programs/LongestPallindromicSubstring.cpp
Labels: hacktoberfest-accepted

#218 Added 2 line fizzbuzz
  Python-Programs/2_line_fizzbuzz.py
Labels: hacktoberfest-accepted

#194 Added linked list programs in cpp
  C++-Programs/merge_sort_LL.cpp
  C++-Programs/ntn_node_from_end_in_ll.cpp
  C++-Programs/sort_ll_of_0_1_2.cpp
Labels: hacktoberfest-accepted

#213 Added a Project
  Python-Programs/US State game/50_states.csv
  Python-Programs/US State game/blank_states_img.gif
  Python-Programs/US State game/main.py
Labels: hacktoberfest-accepted

#160 Added
  C++-Programs/binarytodecimal.cpp
Labels: hacktoberfest-accepted

#266 Create heapsort.cpp
  heapsort.cpp
Labels: hacktoberfest-accepted

#124 Create subtraction.py
  Python-Programs/subtraction.py
Labels: hacktoberfest-accepted

#133 added py program to track location using ip
  Geolocation_IP_tracker.py
Labels: hacktoberfest-accepted

#348 evenOdd
  Java-Programs/evenOdd.java
Labels: hacktoberfest-accepted

#121 Check Pythagorean triplet.cpp
  C++-Programs/Check_Pythagorean_triplet.cpp
Labels: hacktoberfest-accepted

#60 Find-factors.c
  C-Programs/Find_factors.c
Labels: hacktoberfest-accepted

#47 making trangle using loop
  C-Programs/trangle-using-loop.c
Labels: hacktoberfest-accepted

#347 Optimized code for checking if number is prime or not. TC-O(sqrt(n)) #Hacktoberfest2021
  Java-Programs/Prime.java
Labels: hacktoberfest-accepted

#41 area-circle-and-circumference-program.c
  C-Programs/area_circle_and_circumference_program.c
Labels: hacktoberfest-accepted

#243 Added set matrix zeros problem
  Other-Languages/Java/SetMatrixZeros.java
Labels: hacktoberfest-accepted

#43 arithmetic operator
  C-Programs/arithmetic-operator.c
Labels: hacktoberfest-accepted

#102 Created New Python Program for asking name
  Python-Programs/introduction.py
Labels: hacktoberfest-accepted

#210 go conditional statements
  GoLang-Programs/evenOrodd.go
Labels: hacktoberfest-accepted

#158 Create LCM.c
  C-Programs/LCM.c
Labels: hacktoberfest-accepted

#205 timeconverter
  C-Programs/Binary_search.c
  C-Programs/time-convert.c
Labels: hacktoberfest-accepted

#168 Create collection in mongodb in node js
  Nodejs-Programs/mongodb-createcollection.js
Labels: hacktoberfest-accepted

#178 Create con_cat.js
  JavaScript-Programs/con_cat.js
Labels: hacktoberfest-accepted

#349 Added Round robin implementation
  C-Programs/round_robin.c
Labels: hacktoberfest-accepted

#351 Add fibonacci in rust
  Rust-Programs/fibonacci.rs
Labels: hacktoberfest-accepted

#200 Create reverse.cpp
  C++-Programs/reverse.cpp
Labels: hacktoberfest-accepted

#201 Create addnNumber.cpp
  C++-Programs/addnNumber.cpp
Labels: hacktoberfest-accepted

#354 Hello world in Cobol
  Other-Languages/Cobol/hello-world.cob
Labels: hacktoberfest-accepted

#198 Added FrontEnd folder and Name Printer project
  FrontEnd/Name Printer/README.md
  FrontEnd/Name Printer/app.js
  FrontEnd/Name Printer/index.html
  FrontEnd/Name Printer/style.css
Labels: hacktoberfest-accepted

#202 Create FertoCel.cpp
  C++-Programs/FertoCel.cpp
Labels: hacktoberfest-accepted

#204 Create BinarytoOctal.cpp
  C++-Programs/BinarytoOctal.cpp
Labels: hacktoberfest-accepted

#211 Added C++ implementation of BST and LRU Cache code
  C++-Programs/BST_implementation.cpp
  C++-Programs/LRU_Cache_Implementation.cpp
Labels: hacktoberfest-accepted

#224 Create is-two-of-three-boolean-true.java
  Other-Languages/Java/is-two-of-three-boolean-true.java
Labels: hacktoberfest-accepted

#223 Create simple-and-compound-interest.java
  Other-Languages/Java/simple-and-compound-interest.java
Labels: hacktoberfest-accepted

#233 added userdefined type conversion and static members example
  C++-Programs/static_members.cpp
  C++-Programs/userdefined-to-userdefined-typeconversion.cpp
Labels: hacktoberfest-accepted

#235 Create floyd's_shortest_path_algo.c
  C-Programs/floyd's_shortest_path_algo.c
Labels: hacktoberfest-accepted

#352 Merge two sorted linked list
  Java-Programs/merge_two_sorted_linkedlist.java
Labels: hacktoberfest-accepted

#371 Strong password generator using python
  Python-Programs/strong_password_generator.py
Labels: hacktoberfest-accepted

#379 Fahrenheit to celsius
  Python-Programs/temperature_converter.py
Labels: hacktoberfest-accepted

#378 Create form-validation.php
  Other-Languages/php/form-validation.php
Labels: hacktoberfest-accepted

#383 create helloWorld.kt
  Other-Languages/Kotlin/helloWorld.kt
Labels: hacktoberfest-accepted

#402 Created InsertionSort code
  Java-Programs/InsertionSort.java
Labels: hacktoberfest-accepted

#396 Create con_cat.php
  Other-Languages/php/con_cat.php
Labels: hacktoberfest-accepted

#395 added recon.sh
  Other-Languages/Shell-Scripting/recon.sh
Labels: hacktoberfest-accepted

#394 Simple Image downloder for ML and AL projects easy and fast
  Python-Programs/imageDownloderForMLandAI.py
Labels: hacktoberfest-accepted

#393 hactoberfest-2021-python-movie-cli
  Python-Programs/movie-cli/LICENSE
  Python-Programs/movie-cli/README.md
  Python-Programs/movie-cli/main.py
  Python-Programs/movie-cli/requirements.txt
Labels: hacktoberfest-accepted

#392 Create randomNumber-generator.php
  Other-Languages/php/randomNumber-generator.php
Labels: hacktoberfest-accepted

#397 Add Java Program " to rotate array by 180 degrees"
  Java-Programs/rotate_array_180_degrees.java
Labels: hacktoberfest-accepted, waiting for response

#363 added LCA with binary lifting
  C++-Programs/LCA_with_binary_lifting.cpp
Labels: hacktoberfest-accepted

#377 who will pay the bill
  Python-Programs/who_pay_bill.py
Labels: hacktoberfest-accepted

#384 nodejs program to convert csv to json
  Nodejs-Programs/csv_to_json.js
Labels: hacktoberfest-accepted

#387 Adding SwitchCase and Recurssion Program in Java
  Java-Programs/Recurssion.java
  Java-Programs/Switch_case.java
Labels: hacktoberfest-accepted

#388 added virtual base class example in c++
  C++-Programs/virtual-baseclass-diamond-problem.cpp
Labels: hacktoberfest-accepted

#389 QR Code Generator
  Python-Programs/qrcode_generator.py
Labels: hacktoberfest-accepted

#404 Added a java code for BTree
  Java-Programs/BTree.java
Labels: hacktoberfest-accepted

#407 Tower_of_hanoi.java
  Java-Programs/Tower_of_hanoi.java
Labels: hacktoberfest-accepted

#410 Program to add elements of even rows of a matrix
  C++-Programs/add_even_rows.cpp
Labels: hacktoberfest-accepted

#408 added AgeCalculator.py
  Data-Structure-and-Algorithms/Java/sorting/CycleSort.java
Labels: hacktoberfest-accepted

#411 Display Fractals using L-System-Fractal Method
  Python-Programs/LSysFractals.py
Labels: hacktoberfest-accepted

#413 Add Java-fx Simple Calculator with Material UI
  Java-Programs/calculator-javafx/Calculator.iml
  Java-Programs/calculator-javafx/Screeenshoot of Program.png
  Java-Programs/calculator-javafx/src/Main.java
  Java-Programs/calculator-javafx/src/resource/icon.ai
  Java-Programs/calculator-javafx/src/resource/icon.ico
  Java-Programs/calculator-javafx/src/resource/icon.png
  Java-Programs/calculator-javafx/src/resource/icon.svg
  Java-Programs/calculator-javafx/src/style.css
Labels: hacktoberfest-accepted

#414 added Tower of Hanoi Game in C using recursive
  C-Programs/tower_of_hanoi.c
Labels: hacktoberfest-accepted

#424 Create count-vowel.js
  JavaScript-Programs/count-vowel.js
Labels: hacktoberfest-accepted

#442 Regex Validation in js
  JavaScript-Programs/regex-validation.js
Labels: hacktoberfest-accepted

#447 Added a javascript problem
  C++-Programs/DoublyLinkedList.cpp
  Competitive Programming/Codechef Problems/The_One_Who_Knocks_.cpp
  JavaScript-Programs/howsum.js
Labels: hacktoberfest-accepted

#446 Program to multiply two square matrices
  C-Programs/MatrixMultiplication.c
Labels: hacktoberfest-accepted

#441 Created PrimeNumber.py
  Python-Programs/PrimeNumber.py
Labels: hacktoberfest-accepted

#418 Created ArmstsrongNumber code
  Java-Programs/ArmstsrongNumber.java
Labels: hacktoberfest-accepted

#450 A nodejs program to read the given files
  Nodejs-Programs/Read-A-File/app.js
  Nodejs-Programs/Read-A-File/example.html
  Nodejs-Programs/Read-A-File/package.json
Labels: hacktoberfest-accepted

#440 Weather App Node.js
  Nodejs-Programs/Weather-App/.gitignore
  Nodejs-Programs/Weather-App/README.md
  Nodejs-Programs/Weather-App/app.js
  Nodejs-Programs/Weather-App/package-lock.json
  Nodejs-Programs/Weather-App/package.json
Labels: hacktoberfest-accepted

#437 Creaated armstrong.py
  Python-Programs/armstrong.py
Labels: hacktoberfest-accepted

#419 added int-to-words.c
  C-Programs/int-to-words.c
Labels: hacktoberfest-accepted

#420 Created MissingNumber Code
  Java-Programs/MissingNumber.java
Labels: hacktoberfest-accepted

#421 Create ReverseString
  Java-Programs/ReverseString.java
Labels: hacktoberfest-accepted

#416 dart textfield, name, password validator methods
  Dart-Programs/validators.dart
Labels: hacktoberfest-accepted

#412 Searching Algorithms in C
  C-Programs/SearchingAlgorithms/BinarySearchRecursive.c
  C-Programs/SearchingAlgorithms/LinearSearch.c
Labels: hacktoberfest-accepted

#405 Sorting Algorithms in C
  C-Programs/SortingAlgorithms/HeapSort.c
  C-Programs/SortingAlgorithms/InsertionSort.c
  C-Programs/SortingAlgorithms/MergeSort.c
  C-Programs/SortingAlgorithms/RadixSort.c
Labels: hacktoberfest-accepted

#431 display key code of the key
  JavaScript-Programs/key_code/index.css
  JavaScript-Programs/key_code/index.html
  JavaScript-Programs/key_code/index.js
Labels: hacktoberfest-accepted

#470 (bug-fixed) python program which tells that if the sentence you entered is spam or not using a data set and ml
  Python-Programs/spam-detection/spam.csv
  Python-Programs/spam-detection/tracker.py
Labels: hacktoberfest-accepted

#435 Create BubbleSort
  GoLang-Programs/BubbleSort.go
Labels: hacktoberfest-accepted

#433 Multiplication Table for input number
  C-Programs/MultiplicationTable.c
Labels: hacktoberfest-accepted

#451 Create Pyramid.go
  GoLang-Programs/Pyramid.go
Labels: hacktoberfest-accepted

#445 Create Finding_Postfix_Expression.c
  C-Programs/Finding_Postfix_Expression.c
Labels: hacktoberfest-accepted

#491 Hello world program in C#
  C#-Programs/helloworld.cs
Labels: hacktoberfest-accepted

#487 add Next Prayer script
  Other-Languages/Shell-Scripting/nxprayer/Makefile
  Other-Languages/Shell-Scripting/nxprayer/README.md
  Other-Languages/Shell-Scripting/nxprayer/config.mk
  Other-Languages/Shell-Scripting/nxprayer/init.json
  Other-Languages/Shell-Scripting/nxprayer/local_api.cpp
  Other-Languages/Shell-Scripting/nxprayer/nxprayer
  Other-Languages/Shell-Scripting/nxprayer/nxprayer.1
  Other-Languages/Shell-Scripting/nxprayer/remote_api.py
Labels: hacktoberfest-accepted

#456 AgeCalculator - Python
  Python-Programs/AgeCalculator.py
Labels: hacktoberfest-accepted
